### ISSUE TITLE
Few coments on "formatting"

### ISSUE THREAD

**Issue by janhancic** [caplin/css-styleguide#1]
I've read the whole thing and am still formulating an opinion.

I do however have an opinion about this:

> Comments are preceded by a newline.

That should only be the case if the preceding characther is anything but a`{`.

So:

``` css
.foo {
  /** good **/
  float: left;

  /** also good */
  float: left;
  /** bad */
}
```

> Separate different components with a block comment and 3 lines of whitespace:

The rule should be: separate different components into different files.

Those are two obvious things that popped out while reading this. The one other thing that immediately seems wrong is the constant use of `!important`.
